### ISSUE TITLE
enumeration encoding in fields is not reflected in the generated c header

### ISSUE THREAD

**Issue by acaravind** [SystemRDL/PeakRDL-cheader#17]
If the rdl contains
```
field {
    enum xyz{
        XXX= 3'b000 {
            desc = "XXXXX";
        };
        YYY= 3'b001 {
            desc = "YYYY";
        };
    encode = xyz;
} bits[3];
```

I was expecting the generated C header to contain the enumerated data type elaborated in the usual lexical/hierarchical namespace..

This seems to be an omission, in what is otherwise a fantastic, high quality tool!

**Comment by acaravind** [comment]
hi, any update? i just want a confirmation that this is a real issue and i am not mistaken !

**Comment by roowatt** [comment]
This is expected, if you had a look at the open issues you would see that it is discussed in #10

**Comment by acaravind** [comment]
Thank you for the response. Somehow couldn't find it when i did the search!
Glad to know that it is being addressed.

**Comment by roowatt** [comment]
No worries, I have been keeping an eye on  it myself.
